#!/usr/bin/env bash

run_tool() {
	local tool_name="$1"
	if command -v "$tool_name" >/dev/null 2>&1; then
		"$tool_name" "${@:2}"
		if [ $? -ne 0 ]; then exit 1; fi
	else
		echo "warning: '$tool_name' command not found"
		exit 127
	fi
}

run_tool swiftlint --strict --reporter json --quiet
run_tool swiftformat . --lint --reporter json --quiet
